#ifndef MONOPOLY_WEB_COMPAT_DPLAY_H
#define MONOPOLY_WEB_COMPAT_DPLAY_H

#include "windows.h"

typedef DWORD DPID;

typedef struct DPNAME {
    DWORD dwSize;
    DWORD dwFlags;
    LPWSTR lpszShortName;
    LPWSTR lpszLongName;
} DPNAME, *LPDPNAME;
typedef const DPNAME *LPCDPNAME;

typedef struct DPSESSIONDESC2 {
    DWORD dwSize;
    DWORD dwFlags;
    GUID guidInstance;
    GUID guidApplication;
    DWORD dwMaxPlayers;
    DWORD dwCurrentPlayers;
    LPWSTR lpszSessionName;
    LPVOID lpReserved1;
    LPVOID lpReserved2;
    DWORD dwUser1;
    DWORD dwUser2;
    DWORD dwUser3;
    DWORD dwUser4;
} DPSESSIONDESC2, *LPDPSESSIONDESC2;
typedef const DPSESSIONDESC2 *LPCDPSESSIONDESC2;

typedef struct DPCHAT {
    DWORD dwSize;
    DWORD dwFlags;
    LPWSTR lpszMessage;
} DPCHAT, *LPDPCHAT;

typedef struct DPMSG_GENERIC {
    DWORD dwType;
} DPMSG_GENERIC;
typedef struct DPMSG_CREATEPLAYERORGROUP {
    DWORD dwType;
    DWORD dwPlayerType;
    DPID dpId;
} DPMSG_CREATEPLAYERORGROUP;
typedef struct DPMSG_DESTROYPLAYERORGROUP {
    DWORD dwType;
    DWORD dwPlayerType;
    DPID dpId;
} DPMSG_DESTROYPLAYERORGROUP;
typedef struct DPMSG_CHAT {
    DWORD dwType;
    DPID idFromPlayer;
    DPID idToPlayer;
    LPDPCHAT lpChat;
} DPMSG_CHAT;

typedef struct DPLCONNECTION {
    DWORD dwSize;
    DWORD dwFlags;
    LPDPSESSIONDESC2 lpSessionDesc;
    LPDPNAME lpPlayerName;
} DPLCONNECTION, *LPDPLCONNECTION;

typedef struct DPLDATA_PLAYERGUID {
    GUID guidPlayer;
} DPLDATA_PLAYERGUID, *LPDPLDATA_PLAYERGUID;

typedef struct DPLMSG_GETPROPERTY {
    DWORD dwType;
    DWORD dwRequestID;
    GUID guidPlayer;
    GUID guidPropertyTag;
} DPLMSG_GETPROPERTY, *LPDPLMSG_GETPROPERTY;

typedef struct DPLMSG_GETPROPERTYRESPONSE {
    DWORD dwType;
    DWORD dwRequestID;
    GUID guidPlayer;
    GUID guidPropertyTag;
    HRESULT hr;
    DWORD dwDataSize;
    DWORD dwPropertyData;
} DPLMSG_GETPROPERTYRESPONSE, *LPDPLMSG_GETPROPERTYRESPONSE;

typedef struct DPLMSG_SETPROPERTY {
    DWORD dwType;
    DWORD dwRequestID;
    GUID guidPlayer;
    GUID guidPropertyTag;
    DWORD dwDataSize;
    DWORD dwPropertyData[1];
} DPLMSG_SETPROPERTY, *LPDPLMSG_SETPROPERTY;

typedef struct DPLMSG_SETPROPERTYRESPONSE {
    DWORD dwType;
    DWORD dwRequestID;
    GUID guidPlayer;
    GUID guidPropertyTag;
    HRESULT hr;
} DPLMSG_SETPROPERTYRESPONSE, *LPDPLMSG_SETPROPERTYRESPONSE;

typedef BOOL (FAR PASCAL *LPDPENUMCONNECTIONSCALLBACK)(LPCGUID, LPVOID, DWORD, LPCDPNAME, DWORD, LPVOID);
typedef BOOL (FAR PASCAL *LPDPENUMPLAYERSCALLBACK2)(DPID, DWORD, LPCDPNAME, DWORD, LPVOID);
typedef BOOL (FAR PASCAL *LPDPENUMSESSIONSCALLBACK2)(LPCDPSESSIONDESC2, LPDWORD, DWORD, LPVOID);

#define DP_OK S_OK
#define DPERR_GENERIC E_FAIL
#define DPERR_BUFFERTOOSMALL ((HRESULT)0x8007007A)
#define DPERR_NOMESSAGES ((HRESULT)0x88770064)
#define DPERR_OUTOFMEMORY ((HRESULT)0x8007000E)
#define DPERR_NOTLOBBIED ((HRESULT)0x88770070)
#define DPERR_CONNECTING ((HRESULT)0x8877001E)
#define DPERR_SENDTOOBIG ((HRESULT)0x8877001F)
#define DPERR_BUSY ((HRESULT)0x88770002)

#define DPID_SYSMSG 0
#define DPID_ALLPLAYERS ((DPID)0)
#define DPCONNECTION_DIRECTPLAY 0x00000001
#define DPPLAYER_SERVERPLAYER 0x00000001
#define DPPLAYERTYPE_PLAYER 1
#define DPENUMPLAYERS_SERVERPLAYER 0x00000001
#define DPSESSION_KEEPALIVE 0x00000001
#define DPSESSION_CLIENTSERVER 0x00000002
#define DPSESSION_NOMESSAGEID 0x00000004
#define DPSESSION_JOINDISABLED 0x00000008
#define DPSESSION_MIGRATEHOST 0x00000010
#define DPSESSION_NEWPLAYERSDISABLED 0x00000020
#define DPOPEN_CREATE 0x00000001
#define DPOPEN_JOIN 0x00000002
#define DPENUMSESSIONS_AVAILABLE 0x00000001
#define DPENUMSESSIONS_ASYNC 0x00000002
#define DPESC_TIMEDOUT 0x00000001
#define DPRECEIVE_ALL 0x00000001
#define DPRECEIVE_PEEK 0x00000002
#define DPSEND_GUARANTEED 0x00000001
#define DPSET_GUARANTEED 0x00000001
#define DPLCONNECTION_CREATESESSION 0x00000001
#define DPLMSG_STANDARD 0x00000001
#define DPLSYS_GETPROPERTY 0x00000001
#define DPLSYS_GETPROPERTYRESPONSE 0x00000002
#define DPLSYS_SETPROPERTYRESPONSE 0x00000003
#define DPLSYS_SETPROPERTY 0x00000004
#define DPL_NOCONFIRMATION 0xffffffffu
#define DPSYS_CREATEPLAYERORGROUP 0x00000001
#define DPSYS_DESTROYPLAYERORGROUP 0x00000002
#define DPSYS_SESSIONLOST 0x00000003
#define DPSYS_CHAT 0x00000004

static const GUID CLSID_DirectPlay = {0};
static const GUID CLSID_DirectPlayLobby = {0};
static const GUID IID_IDirectPlay4 = {0};
static const GUID IID_IDirectPlayLobby3 = {0};
static const GUID DPLPROPERTY_MessagesSupported = {0};
static const GUID DPLPROPERTY_PlayerGuid = {0};

struct IDirectPlay4 {
    HRESULT EnumConnections(LPCGUID, LPDPENUMCONNECTIONSCALLBACK, LPVOID, DWORD) { return DPERR_GENERIC; }
    HRESULT InitializeConnection(LPVOID, DWORD) { return DPERR_GENERIC; }
    HRESULT CreatePlayer(LPDWORD, LPDPNAME, HANDLE, LPVOID, DWORD, DWORD) { return DPERR_GENERIC; }
    HRESULT EnumPlayers(LPGUID, LPDPENUMPLAYERSCALLBACK2, LPVOID, DWORD) { return DPERR_GENERIC; }
    HRESULT Open(LPDPSESSIONDESC2, DWORD) { return DPERR_GENERIC; }
    HRESULT EnumSessions(LPDPSESSIONDESC2, DWORD, LPDPENUMSESSIONSCALLBACK2, LPVOID, DWORD) { return DPERR_GENERIC; }
    HRESULT Receive(LPDWORD, LPDWORD, DWORD, LPVOID, LPDWORD) { return DPERR_NOMESSAGES; }
    HRESULT Send(DPID, DPID, DWORD, LPVOID, DWORD) { return DPERR_GENERIC; }
    HRESULT SetPlayerName(DPID, LPDPNAME, DWORD) { return DPERR_GENERIC; }
    HRESULT SendChatMessage(DPID, DPID, DWORD, LPDPCHAT) { return DPERR_GENERIC; }
    HRESULT DestroyPlayer(DPID) { return DP_OK; }
    HRESULT Close() { return DP_OK; }
    ULONG Release() { return 0; }
};

struct IDirectPlayLobby3 {
    HRESULT GetConnectionSettings(DWORD, LPDPLCONNECTION, LPDWORD) { return DPERR_NOTLOBBIED; }
    HRESULT SetConnectionSettings(DWORD, DWORD, LPDPLCONNECTION) { return DPERR_GENERIC; }
    HRESULT ConnectEx(DWORD, const GUID&, LPVOID *, void *) { return DPERR_NOTLOBBIED; }
    HRESULT SendLobbyMessage(DWORD, DWORD, LPVOID, DWORD) { return DPERR_GENERIC; }
    HRESULT ReceiveLobbyMessage(DWORD, DWORD, LPDWORD, LPVOID, LPDWORD) { return DPERR_NOMESSAGES; }
    ULONG Release() { return 0; }
};

typedef IDirectPlay4 *LPDIRECTPLAY4;
typedef IDirectPlayLobby3 *LPDIRECTPLAYLOBBY3;

#endif
