#!/usr/bin/env python3
"""Generate build-tree wrappers for legacy case-insensitive includes."""

from __future__ import annotations

import argparse
import os
import posixpath
import re
import shutil
import subprocess
from pathlib import Path


INCLUDE_RE = re.compile(r'^\s*#\s*include\s*([<"])([^>"]+)[>"]', re.MULTILINE)

SOURCE_SUFFIXES = {
    ".c",
    ".cc",
    ".cpp",
    ".cxx",
    ".h",
    ".hh",
    ".hpp",
    ".inl",
    ".H",
    ".CPP",
    ".C",
}

INCLUDE_ROOTS = (
    "",
    "monopoly",
    "artlib",
    "ArtLib",
    "PC3D",
    "Pc3D",
    "pc3D",
    "pc3d",
    "ZLib",
    "zlib",
    "web",
    "web/compat",
    "monopoly/Dat_Mon",
    "monopoly/dat_mon",
    "PC3D/vrml2",
    "PC3D/xvrml",
)

SYSTEM_HEADER_ALIASES = {
    "StdLib.h": "stdlib.h",
    "StdIO.h": "stdio.h",
    "String.h": "string.h",
}


def to_posix(path: str) -> str:
    return path.replace(os.sep, "/")


def norm_case_path(path: str) -> str:
    return posixpath.normpath(path.replace("\\", "/")).lower()


def tracked_files(source_root: Path) -> list[str]:
    try:
        output = subprocess.check_output(
            ["git", "-C", str(source_root), "ls-files", "-z"],
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        files: list[str] = []
        for root, dirs, names in os.walk(source_root):
            dirs[:] = [d for d in dirs if d not in {".git", "build"}]
            for name in names:
                files.append(to_posix(str((Path(root) / name).relative_to(source_root))))
        return sorted(files)

    return sorted(path for path in output.decode("utf-8", "surrogateescape").split("\0") if path)


def source_files(files: list[str]) -> list[str]:
    return [path for path in files if Path(path).suffix in SOURCE_SUFFIXES]


def read_text(path: Path) -> str:
    return path.read_bytes().decode("latin1")


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def wrapper_for(target: Path) -> str:
    return (
        "/* Generated by cmake/generate_casefold_include_overlay.py. */\n"
        f'#include "{target.as_posix()}"\n'
    )


def system_wrapper_for(system_header: str) -> str:
    return (
        "/* Generated by cmake/generate_casefold_include_overlay.py. */\n"
        f"#include_next <{system_header}>\n"
    )


def alias_paths(output_root: Path, base_dir: str, include_name: str) -> set[Path]:
    paths = {
        output_root / base_dir / include_name,
    }
    if "\\" in include_name:
        paths.add(output_root / base_dir / include_name.replace("\\", "/"))
    return paths


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", required=True, type=Path)
    parser.add_argument("--output-root", required=True, type=Path)
    parser.add_argument("--stamp", required=True, type=Path)
    args = parser.parse_args()

    source_root = args.source_root.resolve()
    output_root = args.output_root.resolve()

    files = tracked_files(source_root)
    file_by_casefold: dict[str, str] = {}
    ambiguous: set[str] = set()

    for path in files:
        key = norm_case_path(path)
        if key in file_by_casefold and file_by_casefold[key] != path:
            ambiguous.add(key)
        else:
            file_by_casefold[key] = path

    for key in ambiguous:
        file_by_casefold.pop(key, None)

    if output_root.exists():
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True, exist_ok=True)
    for include_root in INCLUDE_ROOTS:
        (output_root / include_root).mkdir(parents=True, exist_ok=True)

    generated = 0
    for include_name, system_header in SYSTEM_HEADER_ALIASES.items():
        write_if_changed(output_root / include_name, system_wrapper_for(system_header))
        generated += 1

    for source_path in source_files(files):
        source_text = read_text(source_root / source_path)
        source_dir = to_posix(str(Path(source_path).parent))
        if source_dir == ".":
            source_dir = ""

        for delimiter, include_name in INCLUDE_RE.findall(source_text):
            if include_name in SYSTEM_HEADER_ALIASES:
                continue

            candidates: list[tuple[str, str]] = []
            if delimiter == '"':
                candidates.append((source_dir, posixpath.normpath(posixpath.join(source_dir, include_name))))

            for include_root in INCLUDE_ROOTS:
                candidates.append((include_root, posixpath.normpath(posixpath.join(include_root, include_name))))

            actual_path = None
            for _, candidate in candidates:
                actual_path = file_by_casefold.get(norm_case_path(candidate))
                if actual_path:
                    break

            if not actual_path:
                continue

            actual_abs = source_root / actual_path
            content = wrapper_for(actual_abs)

            locations: set[Path] = set()
            if delimiter == '"':
                locations.update(alias_paths(output_root, source_dir, include_name))

            for include_root, candidate in candidates:
                if file_by_casefold.get(norm_case_path(candidate)) == actual_path:
                    locations.update(alias_paths(output_root, include_root, include_name))

            for location in locations:
                write_if_changed(location, content)
                generated += 1

    args.stamp.parent.mkdir(parents=True, exist_ok=True)
    args.stamp.write_text(f"{generated}\n", encoding="utf-8")
    print(f"Generated {generated} case-insensitive include wrappers in {output_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
